[package]
name = "klassify"
description = "Classify chimeric reads based on unique kmer contents"
license-file = "LICENSE"
version = "0.1.6"
edition = "2021"

[dependencies]
bincode = "2.0.1"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
env_logger = "0.11"
flate2 = "1.1.2"
libc = "0.2"
log = "0.4"
needletail = "0.5"
num_cpus = "1.17.0"
perbase = "1.0"
rayon = "1.10"
rust-htslib = "0.39"
serde = { version = "1.0.219", features = ["derive"] }

[[bin]]
name = "klassify"
path = "src/main.rs"
